// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Account struct {
	ID    string      `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
	Role  AccountRole `json:"role"`
	// RFC 3339 timestamp.
	CreatedAt string `json:"createdAt"`
}

type AccountPayload struct {
	Account *Account     `json:"account,omitempty"`
	Errors  []*UserError `json:"errors"`
}

type AddDayInput struct {
	TripID  string `json:"tripID"`
	StageID string `json:"stageID"`
	// Date-only, format YYYY-MM-DD.
	Date        string  `json:"date"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Lat         float64 `json:"lat"`
	Lng         float64 `json:"lng"`
}

type AddStageInput struct {
	TripID      string  `json:"tripID"`
	City        string  `json:"city"`
	Name        *string `json:"name,omitempty"`
	Lat         float64 `json:"lat"`
	Lng         float64 `json:"lng"`
	Description *string `json:"description,omitempty"`
}

type AuthPayload struct {
	// Session token. Present on success, null on error.
	Token   *string      `json:"token,omitempty"`
	Account *Account     `json:"account,omitempty"`
	Errors  []*UserError `json:"errors"`
}

type ChangePasswordInput struct {
	CurrentPassword    string `json:"currentPassword"`
	NewPassword        string `json:"newPassword"`
	NewPasswordConfirm string `json:"newPasswordConfirm"`
}

type CloseTripInput struct {
	FirstDay string `json:"firstDay"`
	LastDay  string `json:"lastDay"`
}

type CreateAccountInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	// Optional. When omitted the account is created without a password — the user must use password reset to set one.
	Password        *string `json:"password,omitempty"`
	PasswordConfirm *string `json:"passwordConfirm,omitempty"`
	// Optional. Defaults to FAMILY. Only FAMILY and EDITOR are allowed.
	Role *AccountRole `json:"role,omitempty"`
}

type CreateTripInput struct {
	Title       string  `json:"title"`
	Country     string  `json:"country"`
	Description *string `json:"description,omitempty"`
	CoverPhoto  *string `json:"coverPhoto,omitempty"`
	Lat         float64 `json:"lat"`
	Lng         float64 `json:"lng"`
	StartDate   *string `json:"startDate,omitempty"`
	EndDate     *string `json:"endDate,omitempty"`
}

type Day struct {
	ID       string   `json:"id"`
	TripID   string   `json:"tripID"`
	StageIDs []string `json:"stageIDs"`
	// Date-only, format YYYY-MM-DD.
	Date string `json:"date"`
	// Null when not provided.
	Title *string `json:"title,omitempty"`
	// Null when not provided.
	Description *string `json:"description,omitempty"`
	// Latitude for map placement.
	Lat float64 `json:"lat"`
	// Longitude for map placement.
	Lng float64 `json:"lng"`
	// RFC 3339 timestamp.
	CreatedAt string `json:"createdAt"`
	// RFC 3339 timestamp.
	UpdatedAt string `json:"updatedAt"`
}

type DayPayload struct {
	Day    *Day         `json:"day,omitempty"`
	Errors []*UserError `json:"errors"`
}

type DeleteAccountPayload struct {
	Success bool         `json:"success"`
	Errors  []*UserError `json:"errors"`
}

type DeleteDayPayload struct {
	Success bool         `json:"success"`
	Errors  []*UserError `json:"errors"`
}

type DeleteMediaPayload struct {
	Success bool         `json:"success"`
	Errors  []*UserError `json:"errors"`
}

type DeleteStagePayload struct {
	Success bool         `json:"success"`
	Errors  []*UserError `json:"errors"`
}

type DeleteTripPayload struct {
	Success bool         `json:"success"`
	Errors  []*UserError `json:"errors"`
}

type Media struct {
	ID          string `json:"id"`
	DayID       string `json:"dayID"`
	TripID      string `json:"tripID"`
	Filename    string `json:"filename"`
	ContentType string `json:"contentType"`
	// Null when not set.
	Caption *string `json:"caption,omitempty"`
	// URL to serve the original file.
	URL string `json:"url"`
	// URL to serve the thumbnail.
	ThumbURL string `json:"thumbUrl"`
	Position int    `json:"position"`
	// RFC 3339 timestamp.
	CreatedAt string `json:"createdAt"`
}

type MediaPayload struct {
	Media  *Media       `json:"media,omitempty"`
	Errors []*UserError `json:"errors"`
}

type ReorderMediaPayload struct {
	Media  []*Media     `json:"media"`
	Errors []*UserError `json:"errors"`
}

type ResetPasswordInput struct {
	Token              string `json:"token"`
	NewPassword        string `json:"newPassword"`
	NewPasswordConfirm string `json:"newPasswordConfirm"`
}

type SetupAdminInput struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type SetupStatusPayload struct {
	Done bool `json:"done"`
}

type Stage struct {
	ID     string `json:"id"`
	TripID string `json:"tripID"`
	City   string `json:"city"`
	// Custom name, if set. Null when not provided.
	Name *string `json:"name,omitempty"`
	// Display name: returns name if set, otherwise city.
	DisplayName string  `json:"displayName"`
	Lat         float64 `json:"lat"`
	Lng         float64 `json:"lng"`
	Description string  `json:"description"`
	// RFC 3339 timestamp.
	CreatedAt string `json:"createdAt"`
	// RFC 3339 timestamp.
	UpdatedAt string `json:"updatedAt"`
}

type StagePayload struct {
	Stage  *Stage       `json:"stage,omitempty"`
	Errors []*UserError `json:"errors"`
}

type Trip struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Country     string `json:"country"`
	Description string `json:"description"`
	CoverPhoto  string `json:"coverPhoto"`
	// Latitude for map placement.
	Lat float64 `json:"lat"`
	// Longitude for map placement.
	Lng float64 `json:"lng"`
	// Date-only, format YYYY-MM-DD. Null when not set.
	StartDate *string `json:"startDate,omitempty"`
	// Date-only, format YYYY-MM-DD. Null when not set.
	EndDate *string    `json:"endDate,omitempty"`
	Status  TripStatus `json:"status"`
	// RFC 3339 timestamp (e.g. 2025-07-01T10:00:00Z).
	CreatedAt string `json:"createdAt"`
	// RFC 3339 timestamp (e.g. 2025-07-01T10:00:00Z).
	UpdatedAt string `json:"updatedAt"`
}

type TripPayload struct {
	Trip   *Trip        `json:"trip,omitempty"`
	Errors []*UserError `json:"errors"`
}

// The date of a day is immutable after creation. To change the date, delete and recreate the day.
type UpdateDayInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Lat         float64 `json:"lat"`
	Lng         float64 `json:"lng"`
}

type UpdateStageInput struct {
	City        string  `json:"city"`
	Name        *string `json:"name,omitempty"`
	Lat         float64 `json:"lat"`
	Lng         float64 `json:"lng"`
	Description *string `json:"description,omitempty"`
}

type UpdateTripInput struct {
	Title       string  `json:"title"`
	Country     string  `json:"country"`
	Description *string `json:"description,omitempty"`
	CoverPhoto  *string `json:"coverPhoto,omitempty"`
	Lat         float64 `json:"lat"`
	Lng         float64 `json:"lng"`
	StartDate   *string `json:"startDate,omitempty"`
	EndDate     *string `json:"endDate,omitempty"`
}

type UserError struct {
	Field   *string `json:"field,omitempty"`
	Message string  `json:"message"`
}

type AccountRole string

const (
	AccountRoleAdmin  AccountRole = "ADMIN"
	AccountRoleEditor AccountRole = "EDITOR"
	AccountRoleFamily AccountRole = "FAMILY"
)

var AllAccountRole = []AccountRole{
	AccountRoleAdmin,
	AccountRoleEditor,
	AccountRoleFamily,
}

func (e AccountRole) IsValid() bool {
	switch e {
	case AccountRoleAdmin, AccountRoleEditor, AccountRoleFamily:
		return true
	}
	return false
}

func (e AccountRole) String() string {
	return string(e)
}

func (e *AccountRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountRole", str)
	}
	return nil
}

func (e AccountRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TripStatus string

const (
	TripStatusDraft     TripStatus = "DRAFT"
	TripStatusPublished TripStatus = "PUBLISHED"
	TripStatusClosed    TripStatus = "CLOSED"
)

var AllTripStatus = []TripStatus{
	TripStatusDraft,
	TripStatusPublished,
	TripStatusClosed,
}

func (e TripStatus) IsValid() bool {
	switch e {
	case TripStatusDraft, TripStatusPublished, TripStatusClosed:
		return true
	}
	return false
}

func (e TripStatus) String() string {
	return string(e)
}

func (e *TripStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TripStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TripStatus", str)
	}
	return nil
}

func (e TripStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TripStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TripStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
