DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS day_stages;
DROP TABLE IF EXISTS days;
DROP TABLE IF EXISTS stages;
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
